"""init

Revision ID: 7ad221d69124
Revises: 4fabfdcad27b
Create Date: 2025-05-17 21:41:56.876778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad221d69124'
down_revision = '4fabfdcad27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
