"""init

Revision ID: c98cfeeaf4b3
Revises: 6962a44ff7f7
Create Date: 2025-05-17 21:54:09.227141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98cfeeaf4b3'
down_revision = '6962a44ff7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
