"""create mahasiswa table

Revision ID: adaebc3b697e
Revises: 79444fd34ed3
Create Date: 2025-05-17 20:17:10.214918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adaebc3b697e'
down_revision = '79444fd34ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
